### ISSUE TITLE
Create a new menu library

### ISSUE THREAD

**Issue by aamott** [aamott/petinator#12]
### **Is your feature request related to a problem? Please describe.**
Currently, the firmware is limited to Arduino and ESP32 due to its reliance on FastAccelStepper, a library based on timers that can run asynchronously. AccelStepper and other libraries that rely on the loop work well until the screen updates. LiquidMenu is just too unoptimized. It clears the entire screen before every single update, and its backend libraries aren't even optimized (LiquidScreen) nor does it allow easy choosing between an i2C display and a normal one like some LCD libraries do. 
Previously, when it was based on AccelStepper, the motor would pause for ~300ms every time the display updated. It was just too slow to use. 

### **Describe the solution you'd like**
I would like a whole new menu library in another file that can be imported just like LiquidMenu. In order for it to be a reliable replacement, it should:
 * Be fast, enough for a stepper motor to run without freezing every screen update.
    * This means being based on the [hd44780 LCD library](https://github.com/duinoWitchery/hd44780 ) since it's the most optimized.
    * Be able to pause writing to the display until the next loop if a certain amount of time passes.
 * Be easy to implement it in the existing system.
    * The current menu system consists of LiquidLines, which go into LiquidScreens, which go into a LiquidMenu. We need at least 2 screens: one for the menu and one for errors. A status screen and a menu screen maybe?
    * On every menu loop, if a variable has changed, it updates it in the menu. 
    * The current menu can bind functions to a line. It would be helpful if it had a built-in way to call an increment and a decrement function.
 * Be self-contained

### **Describe any alternatives you've considered**
Currently there are no alternatives I know of. FastAccelStepper is not supported on enough boards and LiquidMenu is too slow. They have to go. 

### **Additional context**
This is a rather large one, so if you want to help out, this is the main barrier between this firmware and anything not Arduino.

**Comment by aamott** [comment]
Significant progress has been made on the [`timer-free`](https://github.com/aamott/petinator/tree/timer-free) branch implementing this. 
Shows the menu now and doesn't freeze the system for a third of a second every time it updates. But it doesn't function entirely yet. When trying to use the up and down controls, it doesn't move and occasionally reboots the system. I suspect a memory leak somewhere. 

Currently testing in Wokwi: https://wokwi.com/projects/354343237009660929
(Top lcd is for i2c testing, bottom is for direct wired testing)

**Comment by alextrical** [comment]
Have a look at TCMenu it's a well polished project and has a good system for building menus

**Comment by aamott** [comment]
The menu is entirely functional and feels stable now. It could use some code simplifying though. I originally adapted it from the LiquidMenu, so it's got some cleanup to be done, but it's still fast enough to be used in a loop with everything else until the stepper code can be separated out into a portable timer interrupt. Once that's done, I think TCMenu could be a good idea.

For the TMC2209, I do like the idea of the stepper controlling its own timing, but I want to make it so this can be run on as many boards as Marlin using whatever is included with the printer. For now, the [timer-free branch](https://github.com/aamott/petinator/tree/timer-free) gets a pretty good step rate, I think enough for any of the pultruders I've seen so far. Of course, part of that flexibility should probably be communicating with the TMC2209, so that might be an option for higher stepper RPM until the timer interrupt is figured out. 

As a side note, once I've got the new code merged in, I'll convert this to a PlatformIO project to make it just a bit more transferable/familiar to 3D printer users.
